FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        git \
        wget \
        ncbi-blast+ \
        bioperl \
        gzip \
        unzip \
        libjson-perl \
        libtext-csv-perl \
        libpath-tiny-perl \
        liblwp-protocol-https-perl \
        libwww-perl \
        liblist-moreutils-perl \
        libdatetime-perl \
        libnumber-format-perl \
        libfile-slurp-perl \
        make \
        ca-certificates \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /opt

RUN git clone https://github.com/tseemann/any2fasta.git && \
    ln -s /opt/any2fasta/any2fasta /usr/local/bin/any2fasta

# 2. Install Abricate in /opt/abricate
RUN git clone https://github.com/tseemann/abricate.git && \
    ln -s /opt/abricate/bin/abricate /usr/local/bin/abricate && \
    ln -s /opt/abricate/bin/abricate-get_db /usr/local/bin/abricate-get_db && \
    ln -s /opt/abricate/bin/abricate-update /usr/local/bin/abricate-update

# check installation
RUN abricate --check

# 3. Create and set up the VFDB_full database
WORKDIR /opt/abricate/db
RUN mkdir -p vfdb_full && \
    cd vfdb_full && \
    wget -O VFDB_setB_nt.fas.gz \
        http://www.mgc.ac.cn/VFs/Down/VFDB_setB_nt.fas.gz && \
    gunzip VFDB_setB_nt.fas.gz && \
    mv VFDB_setB_nt.fas sequences && \
    cd .. && \
    abricate --setupdb

# 4. Default path and working directory
ENV PATH="/opt/abricate/bin:${PATH}"
WORKDIR /data

CMD ["abricate"]
